### PR TITLE
removing trailing DIRECTORY_SEPARATOR to be able to check single files

### PR DESCRIPTION
**Pull request by greinerdavid**
Hello, I would like to suggest a change to be able to let CodeStyleSniffer check single files and not only folders.

### CODE REVIEW

**Comment by dereuromark** [comment]
Ideally this should only be done for files, but for sake of performance this seems fine.

**Comment by tvaleriy** [comment]
Hi David, 
thank you for contributing into Spryker!
Due to our development process, our public repos are split from just a few monorepos. This usually means directly merging external contributions is a bit harder for us, so typically our developer assigned to the task will manually port it into our monorepo to let the release process publish it again. So I will create an internal ticket for this PR and will let you know here once this change is released.

Best,
Customer Support Engineer

**Comment by greinerdavid** [comment]
Hey Valerie and Mark,

thanks for your ultra fast response and creating an internal ticket for that. 

Is it possible to contribute in a better way?

**Comment by dereuromark** [comment]
No, you did everything all right. We will take care and let you know about the progress and result.
Thank you!

**Comment by dereuromark** [comment]
https://github.com/spryker/development/releases/tag/3.25.5

**Pull request closed without merging**
